### ISSUE TITLE
Search for * gives preg match errors

### ISSUE THREAD

**Issue by OutbackMatt** [palinkas-jo-reggelt/hMailServer_Log_Searcher#2]
If I select a log file then want to  view the whole file by selecting '*' as the search criteria, I get a heap of preg match errors

**Comment by palinkas-jo-reggelt** [comment]
Interesting. The search uses regex. Your entire regex pattern is "/*/" which of course is invalid.

I'll figure out a way to filter out invalid regex.

**Comment by palinkas-jo-reggelt** [comment]
Fixed. Now if an invalid pattern is used in the search string, it will break and display "Invalid Regular Expression Used In Search".

**Comment by palinkas-jo-reggelt** [comment]
> If I select a log file then want to view the whole file by selecting '*' as the search criteria, I get a heap of preg match errors

By the way, you cannot view the whole file (yet). That's intentional. But I do have a plan for that.
