### ISSUE TITLE
Change suggested 

### ISSUE THREAD

**Issue by gotspatel** [palinkas-jo-reggelt/hMailServer_Log_Searcher#3]
https://github.com/palinkas-jo-reggelt/hMailServer_Log_Searcher/blob/52953e05b78a2e3a27cb6437b3db8dbe0b7e76d2/index.php#L39

May I suggest a change as below,

`		if (isset($log_ext)) {
			$defaultFileExt = $log_ext;
		} else {
			// handle the case where $defaultFileExt is not set
		}
`

**Comment by palinkas-jo-reggelt** [comment]
$defaultFileExt is set in the config file. That's why it's the default. ;-)

**Comment by gotspatel** [comment]
https://github.com/palinkas-jo-reggelt/hMailServer_Log_Searcher/blob/52953e05b78a2e3a27cb6437b3db8dbe0b7e76d2/config.dist.php#L9

this to be changed to $defaultFileExt, right?
